### ISSUE TITLE
Support probes without semaphores

### ISSUE THREAD

**Issue by caizixian** [cuviper/rust-libprobe#19]
With the 0.4 version of the crate, usdts are created with semaphores. So when using tools like bpftrace, one has to activate the semaphores in a running process. Is it possible that the crate supports probes with and without semaphores?

**Comment by cuviper** [comment]
I think bpftrace is going to be buggy *in general* if it doesn't activate semaphores in all circumstances. Not just for Rust probes, but that's a big caveat for all USDT probes if semaphores are only sometimes set.

But we can think about how to deal with that here in some kind of override. I don't think it makes sense to have this as part of the probe definition, because then it's like asking "do you want buggy probes or not?" We could have some global compile-time control though, either an "ignore-semaphores" feature at the cargo level, or perhaps a compile-time environment variable along the same lines. It would also be possible in theory to have a runtime environment variable, but then we have to think about how to avoid this in `no_std` cases, and how to cache that so we're not repeatedly reading the environment at every probe site.

**Comment by caizixian** [comment]
Right, I'm using it in performance sensitive settings, so compile-time options sound better to me.

> I think bpftrace is going to be buggy in general if it doesn't activate semaphores in all circumstances. Not just for Rust probes, but that's a big caveat for all USDT probes if semaphores are only sometimes set.

Could you elaborate a bit more? I notice in v3.0 of this crate, all USDT trace points have zero (like 0x0) semaphores when I checked `readelf -n`, so in that case, there's no need to activate semaphores from bpftrace, right?

Thanks!

**Comment by cuviper** [comment]
I mean for SystemTap SDT probes in general, semaphores are a valid part of it, and bpftrace may be missing probes from any number of sources if they don't support this. It's true that prior versions here didn't make use of semaphores, but it's perfectly valid that the current version does.

> Is it possible that the crate supports probes with and without semaphores?

It might still make sense to split this, but I would frame this more in terms of optimization. The old simple version that never checks a semaphore can be compiled down to its single `nop`, if the probe arguments are directly available, while a semaphore-guarded version will wrap the `nop` and arg evaluation with a branch.

Naming is hard though -- I'm not sure what to call these variations...

**Comment by cuviper** [comment]
Let me know what you think of #21!
